//go:build linux

// Complete originals are generated by real M8 executions, with a separate
// failed owner and idle lanes. No verified counters are serialized as authority.
package validator

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/urfoundation/sn/protocol"
)

// The complete expected rows come from original assignment/confirmation paths.
func providerAttemptCompletedOriginalTest(t *testing.T) (*providerAttemptSourceTestFixture, []byte) {
	t.Helper()
	fixture := newProviderAttemptSourceTestFixtureWithCompleted(t, true, true)
	raw, result, err := fixture.source.Read(t.Context(), fixture.artifact)
	if err != nil || result == nil || !result.CutCensusComplete || !result.OwnedRequestsComplete {
		t.Fatal("actual complete original source", err)
	}
	var assignments, confirmations uint64
	rows := map[[16]byte]VerifiedProviderAttemptRow{}
	for _, row := range result.Providers {
		assignments += row.Assignments
		confirmations += row.Confirmations
		if row.NoId == fixture.artifact.NoID {
			rows[row.ClientId] = row
		}
	}
	aMin := result.ReliabilityAMin
	if result.CompleteTrails != aMin || result.FailedTrails != 1 || result.OperatorLanes != 4 || result.Validators != 2 || assignments != 7*aMin+1 || confirmations != 7*aMin {
		t.Fatalf("actual completed/failed/idle census changed: %+v", result)
	}
	eligible, failed, idle := 0, 0, 0
	for _, provider := range fixture.artifact.Providers {
		row := rows[provider.ClientID]
		if provider.Assignments != row.Assignments || provider.Confirmations != row.Confirmations || provider.ReliabilityPPM != protocol.ReliabilityPPM(row.Confirmations, row.Assignments, aMin) || provider.Eligible != (row.Assignments >= aMin) {
			t.Fatal("artifact did not preserve independently replayed original trials")
		}
		if provider.Eligible {
			eligible++
		}
		if row.Assignments > 0 && row.Confirmations == 0 {
			failed++
		}
		if row.Assignments == 0 && row.Confirmations == 0 {
			idle++
		}
	}
	if eligible != 7 || failed != 1 || idle == 0 || len(fixture.artifact.Leaves) == 0 {
		t.Fatalf("complete witness lost earning/failed/idle identities %d/%d/%d", eligible, failed, idle)
	}
	fixture.stateLock.Lock()
	fixture.closed = true
	reads := fixture.reads
	fixture.stateLock.Unlock()
	cold, err := fixture.source.VerifyRetained(t.Context(), fixture.artifact, raw)
	if err != nil || cold == nil || cold.OriginalHash != sha256.Sum256(raw) || cold.WindowHash != result.WindowHash || !cold.OwnedRequestsComplete {
		t.Fatal("completed source cold replay", err)
	}
	fixture.stateLock.Lock()
	defer fixture.stateLock.Unlock()
	if fixture.reads != reads {
		t.Fatal("cold completed source fetched live evidence")
	}
	return fixture, raw
}

// Full M8 confirmation witnesses reach the admitted original AMin without
// turning the independent failed or idle owners into successful providers.
func TestProviderAttemptSourceActualCompletedFailedAndIdleOwners(t *testing.T) {
	providerAttemptCompletedOriginalTest(t)
}

// Sol supplies a distinct protected output directory. Exact failed-only export
// remains separate; these originals contain successful complete M8 paths too.
func TestProviderAttemptSourceExportsActualCompletedFailedIdleOriginals(t *testing.T) {
	root := os.Getenv("URNETWORK_PROVIDER_ATTEMPT_COMPLETED_FIXTURE_DIR")
	if root != "" {
		t.Setenv("URNETWORK_PROVIDER_ATTEMPT_FIXTURE_DIR", root)
	} else {
		t.Setenv("URNETWORK_PROVIDER_ATTEMPT_FIXTURE_DIR", "")
	}
	fixture, raw := providerAttemptCompletedOriginalTest(t)
	if root == "" {
		return
	}
	if !filepath.IsAbs(root) || filepath.Clean(root) != root {
		t.Fatal("completed original export directory must be absolute")
	}
	info, err := os.Lstat(root)
	if err != nil || !info.IsDir() || info.Mode().Perm() != 0700 {
		t.Fatal("completed original export directory not protected", err)
	}
	artifact, err := json.Marshal(fixture.artifact)
	if err != nil {
		t.Fatal(err)
	}
	for name, data := range map[string][]byte{"authority.json": fixture.authorityRaw, "artifact.json": artifact, "original.json": raw} {
		mode := os.FileMode(0400)
		if name == "authority.json" {
			mode = 0600
		}
		file, err := os.OpenFile(filepath.Join(root, name), os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
		if err != nil {
			t.Fatal(err)
		}
		n, writeErr := file.Write(data)
		syncErr := file.Sync()
		closeErr := file.Close()
		if err := errors.Join(writeErr, syncErr, closeErr); err != nil || n != len(data) {
			t.Fatal("completed original export", err)
		}
		got, err := os.ReadFile(filepath.Join(root, name))
		if err != nil || !bytes.Equal(got, data) {
			t.Fatal("completed original export readback", err)
		}
	}
	directory, err := os.Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := errors.Join(directory.Sync(), directory.Close()); err != nil {
		t.Fatal(err)
	}
}
